//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InCity
{
    using System;
    using System.Collections.Generic;
    
    public partial class EventTag
    {
        public int EventId { get; set; }
        public int TagId { get; set; }
        public string data { get; set; }
    
        public virtual Event Event { get; set; }
        public virtual Tag Tag { get; set; }
    }
}
